camera: add missing include
target thumb C++: camera.omap4 <= hardware/ti/omap4xxx/camera/CameraHal.cpp
In file included from hardware/libhardware/include/hardware/camera.h:20:0,
                 from hardware/ti/omap4xxx/camera/inc/CameraHal.h:39,
                 from hardware/ti/omap4xxx/camera/CameraHal_Module.cpp:28:
hardware/libhardware/include/hardware/camera_common.h:27:39: fatal error: system/camera_vendor_tags.h: No such file or directory

Change-Id: I511465566b55ec4acf03725cdb3aa4838076fd7c